apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: users-service
  template:
    metadata:
      labels:
        app: users-service
    spec:
      containers:
        - name: users-service
          image: users-service
          ports:
            - containerPort: 4002
---
apiVersion: v1
kind: Service
metadata:
  name: users-service
spec:
  ports:
    - port: 4002
  selector:
    app: users-service
